name: AutoSprint
main: CraftCamp\AutoSprint\Main
api: [4.0.0]
version: 1.0.1
author: CraftCamp

commands:
  autosprint:
    description: "Toggle AutoSprint"
    permission: autosprint.use
    aliases: ['as']

permissions:
  autosprint.use:
    default: true
